#!/bin/bash

set -e

XBPS_DISTDIR="$(xdistdir)" || exit 1
XBPS_SRCPKGS="${XBPS_DISTDIR}/srcpkgs"

for pkg; do
	pkgdir="$(readlink -f "${pkg}")"

	# Template already in distdir?
	[[ -n "$(find "${XBPS_SRCPKGS}" -samefile "${pkgdir}" -print -quit)" ]] && continue

	pkgname="$(basename "${pkgdir}")"

	# Copy template to distdir for fetchineg
	rm -rf "${XBPS_SRCPKGS:?}/${pkgname}"
	cp -r "${pkgdir}" "${XBPS_SRCPKGS}"

	# Handle subpackages
	"${XBPS_DISTDIR}/xbps-src" show "${pkgname}" \
		| grep '^subpackages:' \
		| cut -f2 \
		| xargs -I'{}' ln -sf "${pkgname}" "${XBPS_DISTDIR}/srcpkgs/{}"
done
